# Generated by Django 3.2.4 on 2021-09-05 19:12

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=30)),
                ('Address_one', models.CharField(max_length=50)),
                ('Address_two', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=80)),
                ('card_number', models.IntegerField()),
                ('card_expiry', models.IntegerField()),
                ('card_cvc', models.IntegerField()),
            ],
        ),
    ]
